# Generated by Django 3.2.6 on 2021-09-04 06:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
