# Generated by Django 3.2.6 on 2021-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
