# Generated by Django 3.2.6 on 2021-09-05 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdata',
            name='name',
            field=models.CharField(default='krishna', max_length=200),
        ),
    ]
